#! /bin/sh
# xfdesktop -D &
# xfce4-panel -d &
#subl &
sxhkd &
picom -b  
#sh -c "sleep 3 && xfconf-query -v -c xfwm4 -p /general/workspace_count -s number"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          15
bspc config active_border_color '#FFFF00'
bspc confIG normal_border_color '#C4C4C4'
bspc confIG normal_border_color '#000000'


bspc config top_padding 30
bspc config bottom_padding 42
bspc config left_padding 0
bspc config right_padding 0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Xfce4-appfinder state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^5' follow=on 
bspc rule -a vlc desktop='^9' follow=on 
bspc rule -a "VirtualBox Manager" desktop='^10' follow=on 
bspc rule -a "Code" desktop='^2' follow=on 
bspc rule -a "jetbrains-rider" desktop='^3' state=floating follow=on 
bspc rule -a "jetbrains-clion" desktop='^1' state=floating follow=on 
bspc rule -a "install4j-burp-StartBurp" desktop='^7' state=floating follow=on 
bspc rule -a Rythmbox desktop='^4' follow=on 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
